# Project-wide Gradle settings.

# Aumentamos la RAM de Gradle a 6GB. Con 24GB totales, esto es seguro y
# le da "aire" al procesador para no trabarse limpiando memoria.
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Forzamos a Gradle a usar todos los núcleos disponibles en paralelo.
org.gradle.parallel=true

# Habilitamos el almacenamiento en caché de compilación (Acelera builds sucesivos).
org.gradle.caching=true

# Mantiene el proceso de Gradle vivo en RAM para que la segunda compilación sea instantánea.
org.gradle.daemon=true

# Configuraciones estándar de Android
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Optimización para KAPT (si usas Room, Hilt o Dagger)
kapt.incremental.apt=true